version: '3.8'

services:
  postgres:
    container_name: postgres
    image: postgres:15.2
    restart: always
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - ${POSTGRES_PORT_OUTSIDE}:${POSTGRES_PORT_INSIDE}

  redis:
    container_name: redis
    image: redis
    env_file:
      - .env
    ports:
      - ${REDIS_PORT_OUTSIDE}:${REDIS_PORT_INSIDE}
    volumes:
      - ./redisdata:/data