version: '3.8'

services:
  postgres1:
    container_name: postgres1
    image: postgres:15.2
    restart: always
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    command: ["postgres", "-c", "log_statement=all"]
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - ${POSTGRES_PORT_OUTSIDE}:${POSTGRES_PORT_INSIDE}

  postgres2:
    container_name: postgres2
    image: postgres:15.2
    restart: always
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER2}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD2}
      - POSTGRES_DB=${POSTGRES_DB2}
    command: [ "postgres", "-c", "log_statement=all" ]
    depends_on:
      - postgres1
    volumes:
      - ./pgdata2:/var/lib/postgresql/data
    ports:
      - ${POSTGRES_PORT_OUTSIDE2}:${POSTGRES_PORT_INSIDE2}

  redis:
    container_name: redis
    image: redis
    env_file:
      - .env
    ports:
      - ${REDIS_PORT_OUTSIDE}:${REDIS_PORT_INSIDE}
    volumes:
      - ./redisdata:/data